### ISSUE TITLE
Unique key identifiers

### ISSUE THREAD

**Issue by bijn** [pjwoodard/larry#21]
We need a way of distinguishing user keys from one another on the HSM. 

Two possible solutions:
- Implement a way of adding tokens to the HSM, which correspond to each user.
- Only use one token and make unique hashes for each key (storing the value in CKA_ID and the key database).

**Comment by pjwoodard** [comment]
My thoughts are that we should implement a way of adding tokens for each user, as those keep the objects separate. Thoughts?

**Comment by bijn** [comment]
Sounds good, I think the only problem with that is that it is SoftHSM specific but otherwise, it will be really easy to implement with `subprocess`.

**Comment by pjwoodard** [comment]
LETS DO # 2

**Comment by pjwoodard** [comment]
;-)

**Comment by mattbarington** [comment]
it would be simpler to modularize each user's data as opposed to querying user specific information

**Comment by mattbarington** [comment]
presuming that we are using the built in web2py database
